###
POST http://localhost:3636/api/create HTTP/1.1
Content-Type: application/json

{
    
    "email": "poff@gmail.com",
    "password":"puff"

}

### 
GET http://localhost:3636/api/users HTTP/1.1

###
GET http://localhost:3636/api/users/63d54c25ac4093d1830d97f1 HTTP/1.1

###
PUT http://localhost:3636/api/update/63d54c25ac4093d1830d97f1 HTTP/1.1
Content-Type: application/json

{
    "email": "tony010101@gmail.com",
    "password":"Carlos866456"
}


###
DELETE http://localhost:3636/api/delete/63d54c25ac4093d1830d97f1 HTTP/1.1

###
POST http://localhost:3636/api/login HTTP/1.1
Content-Type: application/json

{
    
   "email": "tony81191@gmail.com",
   "password": "Carlos8664"

}